### ISSUE TITLE
compiled with errors

### ISSUE THREAD

**Issue by TechSnagit** [garamond13/L4D2-HardRealism#4]
sorry, My English is not so good

compiled with errors:
<img width="1100" alt="1" src="https://github.com/user-attachments/assets/1f8de9f0-bd6a-43a6-9ed5-50bac986d2b6">

Syntax error:  error 100: function prototypes do not match
```
CreateTimer(delay, clear_recently_killed, ZOMBIE_INDEX_CHARGER, TIMER_FLAG_NO_MAPCHANGE);

g_clear_in_attack2_timers[i].timer = CreateTimer(delay, clear_in_attack2, i);

void clear_recently_killed(Handle tiemr, int data)
{
	--g_si_recently_killed[data];
}
```

**Comment by garamond13** [comment]
I could replicate issue on compiler from SourceMod version 1.11. If you want to compile on version 1.11 should change all timer callbacks from `void` to `Action`.

So
```
void clear_recently_killed(Handle tiemr, int data)
{
	--g_si_recently_killed[data];
}
```
change into
```
Action clear_recently_killed(Handle tiemr, int data)
{
	--g_si_recently_killed[data];
}
```
It would be best to compile with the version 1.12 and use it on the SourceMod version 1.12.
